// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t

function occurrence(string){
  const map = new Map();

  for(let i of string){
    map.set(i, (map.get(i) || 0 ) + 1) 
  }
  return map
}


function findTheDifference(s,t){
  
  const s_map = occurrence(s);
  const t_map = occurrence(t);

 for(let [character, t_count] of t_map){

   const s_count = s_map.get(character)
   if(!s_count){
     return character
   }
   else if(s_count !== t_count){
     return character
   }
 }
}
findTheDifference('aea', 'aeaa')

// function findTheDifference(s,t){
//   const set = new Set(s)

//   for( let character of t){
//     if(!set.has(character)){
//       return character
//     }
//   }
//  return undefined
// }
// findTheDifference('aew', 'aewk')